export const ADD_NOTIFICATION = 'ADD_NOTIFICATION'
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION'

export const GET_CONTRACT_TYPES = 'GET_CONTRACT_TYPES'
export const GET_CONTRACT_TYPES_SUCCESS = 'GET_CONTRACT_TYPES_SUCCESS'
export const GET_CONTRACTS = 'GET_CONTRACTS'
export const GET_CONTRACTS_SUCCESS = 'GET_CONTRACTS_SUCCESS'

export const NEW_CONTRACT = 'NEW_CONTRACT'
export const NEW_CONTRACT_SUCCESS = 'NEW_CONTRACT_SUCCESS'

