export const ADD_NOTIFICATION = 'ADD_NOTIFICATION'
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION'

export const GET_CONTRACT_TYPES = 'GET_CONTRACT_TYPES'
export const GET_CONTRACT_TYPES_SUCCESS = 'GET_CONTRACT_TYPES_SUCCESS'

export const GET_DATA = 'GET_DATA'
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS'

export const ADD_DATA = 'ADD_DATA'
export const ADD_DATA_SUCCESS = 'ADD_DATA_SUCCESS'

export const GET_REQUESTS = 'GET_REQUESTS'
export const GET_REQUESTS_SUCCESS = 'GET_REQUESTS_SUCCESS'

export const ADD_REQUEST = 'ADD_REQUESTS'
export const ADD_REQUEST_SUCCESS = 'ADD_REQUESTS_SUCCESS'

export const GET_ACCOUNT = 'GET_ACCOUNT'
export const GET_ACCOUNT_SUCCESS = 'GET_ACCOUNT_SUCCESS'
