export const ADD_NOTIFICATION = 'ADD_NOTIFICATION'
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION'

export const GET_CONTRACT_TYPES = 'GET_CONTRACT_TYPES'
export const GET_CONTRACT_TYPES_SUCCESS = 'GET_CONTRACT_TYPES_SUCCESS'

export const GET_DATASTORE = 'GET_DATASTORE'
export const GET_DATASTORE_SUCCESS = 'GET_DATASTORE_SUCCESS'
export const GET_DATA = 'GET_DATA'
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS'

export const ADD_DATA = 'ADD_DATA'
export const ADD_DATA_SUCCESS = 'ADD_DATA_SUCCESS'

export const GET_REQUESTS = 'GET_REQUESTS'
export const GET_REQUESTS_SUCCESS = 'GET_REQUESTS_SUCCESS'

export const GET_REQUEST = 'GET_REQUEST'
export const GET_REQUEST_SUCCESS = 'GET_REQUEST_SUCCESS'

export const ADD_REQUEST = 'ADD_REQUEST'
export const ADD_REQUEST_SUCCESS = 'ADD_REQUEST_SUCCESS'

export const GET_PROCESSORS = 'GET_PROCESSORS'
export const GET_PROCESSORS_SUCCESS = 'GET_PROCESSORS_SUCCESS'

export const GET_PROCESSOR = 'GET_PROCESSOR'
export const GET_PROCESSOR_SUCCESS = 'GET_PROCESSOR_SUCCESS'

export const ADD_PROCESSOR = 'ADD_PROCESSOR'
export const ADD_PROCESSOR_SUCCESS = 'ADD_PROCESSOR_SUCCESS'

export const GET_ACCOUNTS = 'GET_ACCOUNTS'
export const GET_ACCOUNTS_SUCCESS = 'GET_ACCOUNTS_SUCCESS'

export const GET_ACCOUNT = 'GET_ACCOUNT'
export const GET_ACCOUNT_SUCCESS = 'GET_ACCOUNT_SUCCESS'

export const SET_DEFAULT_ACCOUNT = 'SET_DEFAULT_ACCOUNT'
export const SET_DEFAULT_ACCOUNT_SUCCESS = 'SET_DEFAULT_ACCOUNT_SUCCESS'
